/* Generated By:JavaCC: Do not edit this line. CMMParserConstants.java */
package cc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CMMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int ELSE = 8;
  /** RegularExpression Id. */
  int WHILE = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int READ = 12;
  /** RegularExpression Id. */
  int WRITE = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int BREAK = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int REAL = 17;
  /** RegularExpression Id. */
  int VOID = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int BOOL = 20;
  /** RegularExpression Id. */
  int INTEGER_NUM = 21;
  /** RegularExpression Id. */
  int REAL_NUM = 22;
  /** RegularExpression Id. */
  int CHAR_C = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int SELF_OP = 25;
  /** RegularExpression Id. */
  int UN_LOG_OP = 26;
  /** RegularExpression Id. */
  int BIN_AR_OP_1 = 27;
  /** RegularExpression Id. */
  int BIN_AR_OP_2 = 28;
  /** RegularExpression Id. */
  int LOGIC_OP = 29;
  /** RegularExpression Id. */
  int RELATION_OP = 30;
  /** RegularExpression Id. */
  int BIT_OP = 31;
  /** RegularExpression Id. */
  int ASS_OP = 32;
  /** RegularExpression Id. */
  int IDENTIFIER = 33;
  /** RegularExpression Id. */
  int SEMI = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"read\"",
    "\"write\"",
    "\"return\"",
    "\"break\"",
    "\"int\"",
    "<REAL>",
    "\"void\"",
    "\"char\"",
    "<BOOL>",
    "<INTEGER_NUM>",
    "<REAL_NUM>",
    "<CHAR_C>",
    "<STRING>",
    "<SELF_OP>",
    "\"!\"",
    "<BIN_AR_OP_1>",
    "<BIN_AR_OP_2>",
    "<LOGIC_OP>",
    "<RELATION_OP>",
    "<BIT_OP>",
    "<ASS_OP>",
    "<IDENTIFIER>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
