/* Generated By:JavaCC: Do not edit this line. CMMParserTokenManager.java */
package javacc;

/** Token Manager. */
public class CMMParserTokenManager implements CMMParserConstants
{

  /** Debug output. */
  public static  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public static  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private static final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 33;
            return 4;
         }
         if ((active0 & 0x4000000L) != 0L)
            return 37;
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 33;
            return 69;
         }
         if ((active0 & 0xdf380L) != 0L)
         {
            jjmatchedKind = 33;
            return 45;
         }
         return -1;
      case 1:
         if ((active0 & 0xdfb00L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 45;
         }
         if ((active0 & 0x400L) != 0L)
            return 3;
         if ((active0 & 0x80L) != 0L)
            return 45;
         return -1;
      case 2:
         if ((active0 & 0xcf300L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 45;
         }
         if ((active0 & 0x10800L) != 0L)
            return 45;
         return -1;
      case 3:
         if ((active0 & 0xc1100L) != 0L)
            return 45;
         if ((active0 & 0xe200L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 3;
            return 45;
         }
         return -1;
      case 4:
         if ((active0 & 0xa200L) != 0L)
            return 45;
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 45;
         }
         return -1;
      default :
         return -1;
   }
}
private static final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
static private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
static private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 33:
         return jjStartNfaWithStates_0(0, 26, 37);
      case 40:
         return jjStopAtPos(0, 35);
      case 41:
         return jjStopAtPos(0, 37);
      case 44:
         return jjStopAtPos(0, 36);
      case 59:
         return jjStopAtPos(0, 34);
      case 91:
         return jjStopAtPos(0, 40);
      case 93:
         return jjStopAtPos(0, 41);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x80000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x100L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x10080L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x5000L);
      case 118:
         return jjMoveStringLiteralDfa1_0(0x40000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x2200L);
      case 123:
         return jjStopAtPos(0, 38);
      case 125:
         return jjStopAtPos(0, 39);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
static private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x5000L);
      case 102:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(1, 7, 45);
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x80200L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000L);
      case 111:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(1, 10, 3);
         return jjMoveStringLiteralDfa2_0(active0, 0x40800L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0xa000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
static private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x81000L);
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x42200L);
      case 114:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(2, 11, 45);
         break;
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x100L);
      case 116:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(2, 16, 45);
         return jjMoveStringLiteralDfa3_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
static private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      case 100:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 45);
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 45);
         break;
      case 101:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 45);
         break;
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x200L);
      case 114:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 45);
         break;
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
static private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 9, 45);
         else if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 13, 45);
         break;
      case 107:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(4, 15, 45);
         break;
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
static private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 14, 45);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
static private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 81;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
               case 45:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(45);
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(45);
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 22)
                        kind = 22;
                     jjCheckNAddStates(0, 4);
                  }
                  else if ((0x842000000000L & l) != 0L)
                  {
                     if (kind > 27)
                        kind = 27;
                  }
                  else if ((0x5000000000000000L & l) != 0L)
                  {
                     if (kind > 30)
                        kind = 30;
                  }
                  else if ((0x280000000000L & l) != 0L)
                  {
                     if (kind > 28)
                        kind = 28;
                  }
                  else if (curChar == 61)
                  {
                     if (kind > 32)
                        kind = 32;
                  }
                  else if (curChar == 33)
                     jjCheckNAdd(37);
                  else if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 32;
                  else if (curChar == 34)
                     jjCheckNAddStates(5, 7);
                  else if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 46)
                     jjCheckNAdd(13);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 21)
                        kind = 21;
                     jjCheckNAdd(11);
                  }
                  else if (curChar == 60)
                     jjCheckNAddTwoStates(37, 80);
                  else if (curChar == 62)
                     jjCheckNAddTwoStates(37, 78);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(76, 41);
                  else if (curChar == 43)
                     jjCheckNAddTwoStates(74, 41);
                  else if (curChar == 47)
                     jjCheckNAddStates(8, 10);
                  else if (curChar == 37)
                     jjCheckNAdd(41);
                  else if (curChar == 42)
                     jjCheckNAdd(41);
                  else if (curChar == 61)
                     jjCheckNAdd(37);
                  break;
               case 3:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(45);
                  break;
               case 10:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjCheckNAdd(11);
                  break;
               case 11:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 21)
                     kind = 21;
                  jjCheckNAdd(11);
                  break;
               case 12:
                  if (curChar == 46)
                     jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(13);
                  break;
               case 14:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 15:
                  if ((0xfffffffbfffffbffL & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 17:
                  if ((0x400000400L & l) != 0L)
                     jjCheckNAdd(18);
                  break;
               case 18:
                  if (curChar == 39 && kind > 23)
                     kind = 23;
                  break;
               case 19:
                  if (curChar == 39)
                     jjCheckNAdd(18);
                  break;
               case 20:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 34)
                     jjCheckNAddStates(5, 7);
                  break;
               case 23:
                  if ((0xfffffffbfffffbffL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 25:
                  if ((0x400000400L & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 26:
                  if (curChar == 34 && kind > 24)
                     kind = 24;
                  break;
               case 27:
                  if (curChar == 39)
                     jjCheckNAddStates(5, 7);
                  break;
               case 28:
                  if (curChar == 10)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 39)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 30:
                  if ((0x842000000000L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 31:
                  if ((0x280000000000L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 32:
                  if (curChar == 38 && kind > 29)
                     kind = 29;
                  break;
               case 33:
                  if (curChar == 38)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 36:
                  if ((0x5000000000000000L & l) != 0L && kind > 30)
                     kind = 30;
                  break;
               case 37:
                  if (curChar == 61 && kind > 30)
                     kind = 30;
                  break;
               case 38:
                  if (curChar == 61)
                     jjCheckNAdd(37);
                  break;
               case 39:
                  if (curChar == 33)
                     jjCheckNAdd(37);
                  break;
               case 40:
               case 41:
                  if (curChar == 61 && kind > 32)
                     kind = 32;
                  break;
               case 42:
                  if (curChar == 42)
                     jjCheckNAdd(41);
                  break;
               case 43:
                  if (curChar == 37)
                     jjCheckNAdd(41);
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAddStates(0, 4);
                  break;
               case 47:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(47);
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(48, 49);
                  break;
               case 49:
                  if (curChar == 46 && kind > 22)
                     kind = 22;
                  break;
               case 50:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(50, 51);
                  break;
               case 51:
                  if (curChar == 46)
                     jjCheckNAdd(52);
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 22)
                     kind = 22;
                  jjCheckNAdd(52);
                  break;
               case 53:
                  if (curChar == 47)
                     jjCheckNAddStates(8, 10);
                  break;
               case 54:
                  if (curChar == 47)
                     jjCheckNAddStates(11, 13);
                  break;
               case 55:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(11, 13);
                  break;
               case 56:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 57:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 58:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 59:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(60, 61);
                  break;
               case 60:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(60, 61);
                  break;
               case 61:
                  if (curChar == 42)
                     jjAddStates(14, 15);
                  break;
               case 62:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(63, 61);
                  break;
               case 63:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(63, 61);
                  break;
               case 64:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 73:
                  if (curChar == 43)
                     jjCheckNAddTwoStates(74, 41);
                  break;
               case 74:
                  if (curChar == 43 && kind > 25)
                     kind = 25;
                  break;
               case 75:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(76, 41);
                  break;
               case 76:
                  if (curChar == 45 && kind > 25)
                     kind = 25;
                  break;
               case 77:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(37, 78);
                  break;
               case 78:
                  if (curChar == 62 && kind > 31)
                     kind = 31;
                  break;
               case 79:
                  if (curChar == 60)
                     jjCheckNAddTwoStates(37, 80);
                  break;
               case 80:
                  if (curChar == 60 && kind > 31)
                     kind = 31;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(45);
                  }
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 69:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(45);
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 71;
                  else if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 68;
                  break;
               case 5:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(45);
                  }
                  else if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 34;
                  else if (curChar == 92)
                     jjAddStates(16, 17);
                  if (curChar == 102)
                     jjAddStates(18, 19);
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 8;
                  else if (curChar == 100)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 3:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(45);
                  }
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 0:
                  if (curChar == 101 && kind > 17)
                     kind = 17;
                  break;
               case 1:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 2:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 6:
                  if (curChar == 101 && kind > 20)
                     kind = 20;
                  break;
               case 7:
                  if (curChar == 117)
                     jjCheckNAdd(6);
                  break;
               case 8:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 9:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 8;
                  break;
               case 15:
                  if ((0xffffffffefffffffL & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 16:
                  if (curChar == 92)
                     jjAddStates(16, 17);
                  break;
               case 17:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 23:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAddStates(5, 7);
                  break;
               case 24:
                  if (curChar == 92)
                     jjAddStates(20, 21);
                  break;
               case 25:
                  if (curChar == 92)
                     jjCheckNAddStates(5, 7);
                  break;
               case 34:
                  if (curChar == 124 && kind > 29)
                     kind = 29;
                  break;
               case 35:
                  if (curChar == 124)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 44:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(45);
                  break;
               case 45:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(45);
                  break;
               case 55:
                  jjAddStates(11, 13);
                  break;
               case 60:
                  jjCheckNAddTwoStates(60, 61);
                  break;
               case 62:
               case 63:
                  jjCheckNAddTwoStates(63, 61);
                  break;
               case 65:
                  if (curChar == 102)
                     jjAddStates(18, 19);
                  break;
               case 66:
                  if (curChar == 116 && kind > 17)
                     kind = 17;
                  break;
               case 67:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 68:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 67;
                  break;
               case 70:
                  if (curChar == 115)
                     jjCheckNAdd(6);
                  break;
               case 71:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 15:
                  if ((jjbitVec0[i2] & l2) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 23:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(5, 7);
                  break;
               case 55:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(11, 13);
                  break;
               case 60:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(60, 61);
                  break;
               case 62:
               case 63:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(63, 61);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 81 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   47, 48, 49, 50, 51, 23, 24, 26, 54, 59, 41, 55, 56, 58, 62, 64, 
   17, 21, 69, 72, 25, 29, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, "\151\146", "\145\154\163\145", 
"\167\150\151\154\145", "\144\157", "\146\157\162", "\162\145\141\144", "\167\162\151\164\145", 
"\162\145\164\165\162\156", "\142\162\145\141\153", "\151\156\164", null, "\166\157\151\144", 
"\143\150\141\162", null, null, null, null, null, null, "\41", null, null, null, null, null, null, 
null, "\73", "\50", "\54", "\51", "\173", "\175", "\133", "\135", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x3ffffffff81L, 
};
static final long[] jjtoSkip = {
   0x7eL, 
};
static protected SimpleCharStream input_stream;
static private final int[] jjrounds = new int[81];
static private final int[] jjstateSet = new int[162];
static protected char curChar;
/** Constructor. */
public CMMParserTokenManager(SimpleCharStream stream){
   if (input_stream != null)
      throw new TokenMgrError("ERROR: Second call to constructor of static lexer. You must use ReInit() to initialize the static variables.", TokenMgrError.STATIC_LEXER_ERROR);
   input_stream = stream;
}

/** Constructor. */
public CMMParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
static private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 81; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
static public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
static public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

static protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

static int curLexState = 0;
static int defaultLexState = 0;
static int jjnewStateCnt;
static int jjround;
static int jjmatchedPos;
static int jjmatchedKind;

/** Get the next Token. */
public static Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

static private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
static private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
static private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

static private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
